language: java

env:
  - SCALA_VERSION=2.11 LAGOM_VERSION=1.4.15
  - SCALA_VERSION=2.12 LAGOM_VERSION=1.5.1
  - SCALA_VERSION=2.13 LAGOM_VERSION=1.6.0-M5

jdk:
  - openjdk8

matrix:
  fast_finish: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean check -PlagomVersion=$LAGOM_VERSION -PscalaBinaryVersion=$SCALA_VERSION

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - echo $GPG_SECRET_KEYS | base64 --decode > $HOME/.gnupg/taymyr.gpg

deploy:
  # Deploy releases
  - provider: script
    script: bin/publish-release
    skip_cleanup: true
    on:
      tags: true
  # Deploy snapshots
  - provider: script
    script: bin/publish-snapshots
    skip_cleanup: true
    on:
      branch: master
      tags: false

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/9e04688b0ae124f5a047"
      - "https://webhooks.gitter.im/e/869b1a645dc46645e619"
    on_success: change
    on_failure: always
    on_start: never